using System.Collections.Generic;
using ai;
namespace xn.world 
{
    internal struct CultivationStatsConfig
    {
        public int stamina;             
        public int health;              
        public int healthRegenPerYear;  
        public int damage;              
        public int speed;               
        public int lifespan;            
        public int command;             
        public int organization;        
        public int attackSpeed;         
        public int intelligence;        
        public float critPercent;       
        public float damagePercent;     
        public float healthPercent;     
        public int accuracy;            
        public int range;               
        public int knockback;           
        public int knockbackResist;     
        public int dodge;               
        public int hit;                 
        public int weight;              
        public float armorPercent;      
        public float scale;             
        public float speedMultiplier;   
        public int areaOfEffect;        
        public int targets;             
        public int lingliMax;           
        public int lingliRegenPerYear;  
        public int yuanliMax;           
        public int yuanliRegenPerYear;  
        public int nieliMax;            
        public int nieliRegenPerYear;   
    }
    internal static class CultivationStatsConfigTable
    {
        private static readonly Dictionary<string, CultivationStatsConfig> _realmConfigs =
            new Dictionary<string, CultivationStatsConfig>
            {
                ["realm_01_qi"] = new CultivationStatsConfig
                {
                    stamina = 20,
                    health = 1000,
                    healthRegenPerYear = 5,
                    damage = 20,
                    speed = 4,
                    lifespan = 24,
                    command = 0,
                    organization = 0,
                    attackSpeed = 0,
                    intelligence = 15,
                    critPercent = 0f,
                    damagePercent = 0f,
                    healthPercent = 0f,
                    accuracy = 10,
                    range = 0,
                    knockback = 0,
                    knockbackResist = 0,
                    dodge = 10,
                    hit = 10,
                    weight = 0,
                    armorPercent = 5f,
                    scale = 0f,                 
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 100,
                    lingliRegenPerYear = 10,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_02_foundation"] = new CultivationStatsConfig
                {
                    stamina = 70,
                    health = 3000,
                    healthRegenPerYear = 15,
                    damage = 150,
                    speed = 7,
                    lifespan = 80,
                    command = 1,
                    organization = 0,
                    attackSpeed = 1,
                    intelligence = 40,
                    critPercent = 0.03f,
                    damagePercent = 0.03f,
                    healthPercent = 0.03f,
                    accuracy = 20,
                    range = 1,
                    knockback = 0,
                    knockbackResist = 0,
                    dodge = 20,
                    hit = 20,
                    weight = 15,
                    armorPercent = 9f,
                    scale = 0.002f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 200,
                    lingliRegenPerYear = 20,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_03_core"] = new CultivationStatsConfig
                {
                    stamina = 150,
                    health = 8500,
                    healthRegenPerYear = 50,
                    damage = 400,
                    speed = 12,
                    lifespan = 300,
                    command = 2,
                    organization = 2,
                    attackSpeed = 2,
                    intelligence = 80,
                    critPercent = 0.05f,
                    damagePercent = 0.05f,
                    healthPercent = 0.05f,
                    accuracy = 40,
                    range = 2,
                    knockback = 1,
                    knockbackResist = 1,
                    dodge = 40,
                    hit = 40,
                    weight = 25,
                    armorPercent = 14f,
                    scale = 0.005f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 500,
                    lingliRegenPerYear = 35,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_04_nascent"] = new CultivationStatsConfig
                {
                    stamina = 400,
                    health = 15000,
                    healthRegenPerYear = 150,
                    damage = 800,
                    speed = 17,
                    lifespan = 800,
                    command = 3,
                    organization = 3,
                    attackSpeed = 3,
                    intelligence = 120,
                    critPercent = 0.07f,
                    damagePercent = 0.07f,
                    healthPercent = 0.07f,
                    accuracy = 70,
                    range = 3,
                    knockback = 2,
                    knockbackResist = 2,
                    dodge = 70,
                    hit = 70,
                    weight = 35,
                    armorPercent = 19f,
                    scale = 0.01f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 800,
                    lingliRegenPerYear = 50,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_05_deity"] = new CultivationStatsConfig
                {
                    stamina = 800,
                    health = 30000,
                    healthRegenPerYear = 500,
                    damage = 2000,
                    speed = 50,
                    lifespan = 1600,
                    command = 4,
                    organization = 5,
                    attackSpeed = 4,
                    intelligence = 170,
                    critPercent = 0.09f,
                    damagePercent = 0.09f,
                    healthPercent = 0.09f,
                    accuracy = 100,
                    range = 4,
                    knockback = 3,
                    knockbackResist = 3,
                    dodge = 100,
                    hit = 100,
                    weight = 45,
                    armorPercent = 25f,
                    scale = 0.015f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 1500,
                    lingliRegenPerYear = 80,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_06_infantchg"] = new CultivationStatsConfig
                {
                    stamina = 1300,
                    health = 55000,
                    healthRegenPerYear = 1200,
                    damage = 5000,
                    speed = 35,
                    lifespan = 4000,
                    command = 5,
                    organization = 7,
                    attackSpeed = 5,
                    intelligence = 220,
                    critPercent = 0.11f,
                    damagePercent = 0.11f,
                    healthPercent = 0.11f,
                    accuracy = 120,
                    range = 5,
                    knockback = 4,
                    knockbackResist = 4,
                    dodge = 120,
                    hit = 120,
                    weight = 55,
                    armorPercent = 33f,
                    scale = 0.02f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 2500,
                    lingliRegenPerYear = 120,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_07_wending"] = new CultivationStatsConfig
                {
                    stamina = 2000,
                    health = 95000,
                    healthRegenPerYear = 3000,
                    damage = 10000,
                    speed = 100,
                    lifespan = 10000,
                    command = 6,
                    organization = 8,
                    attackSpeed = 6,
                    intelligence = 280,
                    critPercent = 0.13f,
                    damagePercent = 0.13f,
                    healthPercent = 0.13f,
                    accuracy = 140,
                    range = 6,
                    knockback = 5,
                    knockbackResist = 5,
                    dodge = 140,
                    hit = 140,
                    weight = 70,
                    armorPercent = 43f,
                    scale = 0.03f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 5000,
                    lingliRegenPerYear = 180,
                    yuanliMax = 50,
                    yuanliRegenPerYear = 1,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_08_kuinie"] = new CultivationStatsConfig
                {
                    stamina = 4000,
                    health = 350000,
                    healthRegenPerYear = 50000,
                    damage = 20000,
                    speed = 90,
                    lifespan = 140000,
                    command = 8,
                    organization = 12,
                    attackSpeed = 8,
                    intelligence = 400,
                    critPercent = 0.17f,
                    damagePercent = 0.17f,
                    healthPercent = 0.17f,
                    accuracy = 180,
                    range = 10,
                    knockback = 7,
                    knockbackResist = 7,
                    dodge = 180,
                    hit = 180,
                    weight = 110,
                    armorPercent = 56f,
                    scale = 0.05f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000,
                    lingliRegenPerYear = 300,
                    yuanliMax = 100,
                    yuanliRegenPerYear = 10,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_09_jingnie"] = new CultivationStatsConfig
                {
                    stamina = 5000,
                    health = 1100000,
                    healthRegenPerYear = 150000,
                    damage = 60000,
                    speed = 110,
                    lifespan = 400000,
                    command = 9,
                    organization = 14,
                    attackSpeed = 9,
                    intelligence = 470,
                    critPercent = 0.19f,
                    damagePercent = 0.19f,
                    healthPercent = 0.19f,
                    accuracy = 200,
                    range = 11,
                    knockback = 7,
                    knockbackResist = 7,
                    dodge = 200,
                    hit = 200,
                    weight = 130,
                    armorPercent = 72f,
                    scale = 0.06f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 20000,
                    lingliRegenPerYear = 500,
                    yuanliMax = 300,
                    yuanliRegenPerYear = 20,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["realm_10_suinie"] = new CultivationStatsConfig
                {
                    stamina = 6000,
                    health = 3500000,
                    healthRegenPerYear = 500000,
                    damage = 200000,
                    speed = 130,
                    lifespan = 2000000,
                    command = 10,
                    organization = 16,
                    attackSpeed = 10,
                    intelligence = 550,
                    critPercent = 0.21f,
                    damagePercent = 0.21f,
                    healthPercent = 0.21f,
                    accuracy = 220,
                    range = 12,
                    knockback = 8,
                    knockbackResist = 8,
                    dodge = 240,
                    hit = 240,
                    weight = 150,
                    armorPercent = 92f,
                    scale = 0.08f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 50000,
                    lingliRegenPerYear = 1000,
                    yuanliMax = 500,
                    yuanliRegenPerYear = 30,
                    nieliMax = 20,
                    nieliRegenPerYear = 1
                },
                ["realm_11_kongnie"] = new CultivationStatsConfig
                {
                    stamina = 7000,
                    health = 11000000,
                    healthRegenPerYear = 1500000,
                    damage = 1000000,
                    speed = 155,
                    lifespan = 8000000,
                    command = 11,
                    organization = 18,
                    attackSpeed = 11,
                    intelligence = 650,
                    critPercent = 0.23f,
                    damagePercent = 0.23f,
                    healthPercent = 0.23f,
                    accuracy = 240,
                    range = 14,
                    knockback = 8,
                    knockbackResist = 8,
                    dodge = 290,
                    hit = 290,
                    weight = 180,
                    armorPercent = 110f,
                    scale = 0.10f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 100000,
                    lingliRegenPerYear = 3000,
                    yuanliMax = 1000,
                    yuanliRegenPerYear = 50,
                    nieliMax = 100,
                    nieliRegenPerYear = 5
                },
                ["realm_12_kongling"] = new CultivationStatsConfig
                {
                    stamina = 8000,
                    health = 28000000,
                    healthRegenPerYear = 4000000,
                    damage = 3000000,
                    speed = 180,
                    lifespan = 20000000,
                    command = 12,
                    organization = 21,
                    attackSpeed = 12,
                    intelligence = 750,
                    critPercent = 0.25f,
                    damagePercent = 0.25f,
                    healthPercent = 0.25f,
                    accuracy = 260,
                    range = 16,
                    knockback = 9,
                    knockbackResist = 9,
                    dodge = 350,
                    hit = 350,
                    weight = 220,
                    armorPercent = 130f,
                    scale = 0.13f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 500000,
                    lingliRegenPerYear = 8000,
                    yuanliMax = 5000,
                    yuanliRegenPerYear = 200,
                    nieliMax = 200,
                    nieliRegenPerYear = 10
                },
                ["realm_13_kongxuan"] = new CultivationStatsConfig
                {
                    stamina = 9000,
                    health = 70000000,
                    healthRegenPerYear = 10000000,
                    damage = 10000000,
                    speed = 210,
                    lifespan = 60000000,
                    command = 13,
                    organization = 24,
                    attackSpeed = 13,
                    intelligence = 850,
                    critPercent = 0.27f,
                    damagePercent = 0.27f,
                    healthPercent = 0.27f,
                    accuracy = 280,
                    range = 17,
                    knockback = 9,
                    knockbackResist = 9,
                    dodge = 410,
                    hit = 410,
                    weight = 260,
                    armorPercent = 150f,
                    scale = .16f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 2000000,
                    lingliRegenPerYear = 20000,
                    yuanliMax = 20000,
                    yuanliRegenPerYear = 500,
                    nieliMax = 2500,
                    nieliRegenPerYear = 50
                },
                ["realm_14_gtianzun"] = new CultivationStatsConfig
                {
                    stamina = 10000,
                    health = 140000000,
                    healthRegenPerYear = 20000000,
                    damage = 42000000,
                    speed = 250,
                    lifespan = 200000000,
                    command = 15,
                    organization = 30,
                    attackSpeed = 15,
                    intelligence = 999,
                    critPercent = 0.30f,
                    damagePercent = 0.30f,
                    healthPercent = 0.30f,
                    accuracy = 500,
                    range = 20,
                    knockback = 10,
                    knockbackResist = 10,
                    dodge = 500,
                    hit = 500,
                    weight = 290,
                    armorPercent = 186f,
                    scale = 0.19f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000000,
                    lingliRegenPerYear = 50000,
                    yuanliMax = 100000,
                    yuanliRegenPerYear = 2000,
                    nieliMax = 8000,
                    nieliRegenPerYear = 200
                },
                ["realm_15_half_tatian"] = new CultivationStatsConfig
                {
                    stamina = 15000,
                    health = 600000000,
                    healthRegenPerYear = 80000000,
                    damage = 240000000,
                    speed = 350,
                    lifespan = 800000000,
                    command = 18,
                    organization = 35,
                    attackSpeed = 18,
                    intelligence = 1300,
                    critPercent = 0.35f,
                    damagePercent = 0.35f,
                    healthPercent = 0.35f,
                    accuracy = 380,
                    range = 25,
                    knockback = 12,
                    knockbackResist = 12,
                    dodge = 650,
                    hit = 630,
                    weight = 295,
                    armorPercent = 260f,
                    scale = 0.22f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 100000000,
                    lingliRegenPerYear = 200000,
                    yuanliMax = 1000000,
                    yuanliRegenPerYear = 8000,
                    nieliMax = 50000,
                    nieliRegenPerYear = 1000
                },
                ["realm_16_tatian"] = new CultivationStatsConfig
                {
                    stamina = 25000,
                    health = 1450000000,
                    healthRegenPerYear = 200000000,
                    damage = 600000000,
                    speed = 500,
                    lifespan = 1400000000,
                    command = 20,
                    organization = 40,
                    attackSpeed = 20,
                    intelligence = 2000,
                    critPercent = 0.50f,
                    damagePercent = 0.50f,
                    healthPercent = 0.05f,
                    accuracy = 650,
                    range = 30,
                    knockback = 20,
                    knockbackResist = 20,
                    dodge = 1000,
                    hit = 950,
                    weight = 300,
                    armorPercent = 400f,
                    scale = 0.25f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 900000000,
                    lingliRegenPerYear = 1000000,
                    yuanliMax = 100000000,
                    yuanliRegenPerYear = 50000,
                    nieliMax = 100000000,
                    nieliRegenPerYear = 5000
                },
                ["ancient_01_star"] = new CultivationStatsConfig
                {
                    stamina = 200,
                    health = 10000,
                    healthRegenPerYear = 100,
                    damage = 50,
                    speed = 15,
                    lifespan = 160,
                    command = 0,
                    organization = 0,
                    attackSpeed = 3,
                    intelligence = 10,
                    critPercent = 0.01f,
                    damagePercent = 0.01f,
                    healthPercent = 0.08f,
                    accuracy = 40,
                    range = 0,
                    knockback = 3,
                    knockbackResist = 3,
                    dodge = 40,
                    hit = 40,
                    weight = 50,
                    armorPercent = 12f,
                    scale = 0.03f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 500,
                    lingliRegenPerYear = 35,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["ancient_02_star"] = new CultivationStatsConfig
                {
                    stamina = 1000,
                    health = 50000,
                    healthRegenPerYear = 1000,
                    damage = 360,
                    speed = 30,
                    lifespan = 1000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 5,
                    intelligence = 20,
                    critPercent = 0.02f,
                    damagePercent = 0.02f,
                    healthPercent = 0.12f,
                    accuracy = 100,
                    range = 0,
                    knockback = 5,
                    knockbackResist = 5,
                    dodge = 100,
                    hit = 100,
                    weight = 80,
                    armorPercent = 23f,
                    scale = 0.05f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 1500,
                    lingliRegenPerYear = 80,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["ancient_03_star"] = new CultivationStatsConfig
                {
                    stamina = 2500,
                    health = 100000,
                    healthRegenPerYear = 6000,
                    damage = 2200,
                    speed = 60,
                    lifespan = 6000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 7,
                    intelligence = 30,
                    critPercent = 0.03f,
                    damagePercent = 0.03f,
                    healthPercent = 0.15f,
                    accuracy = 140,
                    range = 0,
                    knockback = 7,
                    knockbackResist = 7,
                    dodge = 140,
                    hit = 140,
                    weight = 120,
                    armorPercent = 39f,
                    scale = 0.07f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 5000,
                    lingliRegenPerYear = 180,
                    yuanliMax = 50,
                    yuanliRegenPerYear = 1,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["ancient_04_star"] = new CultivationStatsConfig
                {
                    stamina = 5000,
                    health = 500000,
                    healthRegenPerYear = 100000,
                    damage = 28000,
                    speed = 100,
                    lifespan = 100000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 9,
                    intelligence = 40,
                    critPercent = 0.04f,
                    damagePercent = 0.04f,
                    healthPercent = 0.20f,
                    accuracy = 180,
                    range = 0,
                    knockback = 9,
                    knockbackResist = 9,
                    dodge = 180,
                    hit = 180,
                    weight = 150,
                    armorPercent = 61f,
                    scale = 0.10f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000,
                    lingliRegenPerYear = 300,
                    yuanliMax = 100,
                    yuanliRegenPerYear = 10,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["ancient_05_star"] = new CultivationStatsConfig
                {
                    stamina = 6000,
                    health = 1500000,
                    healthRegenPerYear = 300000,
                    damage = 80000,
                    speed = 120,
                    lifespan = 300000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 10,
                    intelligence = 50,
                    critPercent = 0.05f,
                    damagePercent = 0.05f,
                    healthPercent = 0.22f,
                    accuracy = 200,
                    range = 0,
                    knockback = 10,
                    knockbackResist = 10,
                    dodge = 200,
                    hit = 200,
                    weight = 180,
                    armorPercent = 89f,
                    scale = 0.14f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 20000,
                    lingliRegenPerYear = 500,
                    yuanliMax = 300,
                    yuanliRegenPerYear = 20,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["ancient_06_star"] = new CultivationStatsConfig
                {
                    stamina = 7000,
                    health = 4500000,
                    healthRegenPerYear = 900000,
                    damage = 260000,
                    speed = 140,
                    lifespan = 1600000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 12,
                    intelligence = 60,
                    critPercent = 0.06f,
                    damagePercent = 0.06f,
                    healthPercent = 0.24f,
                    accuracy = 220,
                    range = 0,
                    knockback = 12,
                    knockbackResist = 12,
                    dodge = 240,
                    hit = 240,
                    weight = 220,
                    armorPercent = 122f,
                    scale = 0.18f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 50000,
                    lingliRegenPerYear = 1000,
                    yuanliMax = 500,
                    yuanliRegenPerYear = 30,
                    nieliMax = 20,
                    nieliRegenPerYear = 1
                },
                ["ancient_07_star"] = new CultivationStatsConfig
                {
                    stamina = 8000,
                    health = 15000000,
                    healthRegenPerYear = 3000000,
                    damage = 1300000,
                    speed = 165,
                    lifespan = 6000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 13,
                    intelligence = 70,
                    critPercent = 0.07f,
                    damagePercent = 0.07f,
                    healthPercent = 0.26f,
                    accuracy = 240,
                    range = 0,
                    knockback = 13,
                    knockbackResist = 13,
                    dodge = 290,
                    hit = 290,
                    weight = 250,
                    armorPercent = 160f,
                    scale = 0.22f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 100000,
                    lingliRegenPerYear = 3000,
                    yuanliMax = 1000,
                    yuanliRegenPerYear = 50,
                    nieliMax = 100,
                    nieliRegenPerYear = 5
                },
                ["ancient_08_star"] = new CultivationStatsConfig
                {
                    stamina = 9800,
                    health = 140000000,
                    healthRegenPerYear = 30000000,
                    damage = 30000000,
                    speed = 240,
                    lifespan = 100000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 15,
                    intelligence = 80,
                    critPercent = 0.08f,
                    damagePercent = 0.08f,
                    healthPercent = 0.29f,
                    accuracy = 280,
                    range = 0,
                    knockback = 15,
                    knockbackResist = 15,
                    dodge = 410,
                    hit = 410,
                    weight = 290,
                    armorPercent = 204f,
                    scale = 0.26f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 2000000,
                    lingliRegenPerYear = 20000,
                    yuanliMax = 20000,
                    yuanliRegenPerYear = 500,
                    nieliMax = 2500,
                    nieliRegenPerYear = 50
                },
                ["ancient_09_star"] = new CultivationStatsConfig
                {
                    stamina = 11000,
                    health = 200000000,
                    healthRegenPerYear = 45000000,
                    damage = 56000000,
                    speed = 275,
                    lifespan = 160000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 17,
                    intelligence = 90,
                    critPercent = 0.10f,
                    damagePercent = 0.10f,
                    healthPercent = 0.32f,
                    accuracy = 380,
                    range = 0,
                    knockback = 17,
                    knockbackResist = 17,
                    dodge = 650,
                    hit = 630,
                    weight = 330,
                    armorPercent = 336f,
                    scale = 0.30f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000000,
                    lingliRegenPerYear = 50000,
                    yuanliMax = 100000,
                    yuanliRegenPerYear = 2000,
                    nieliMax = 8000,
                    nieliRegenPerYear = 200
                },
                ["ancient_10_star"] = new CultivationStatsConfig
                {
                    stamina = 18000,
                    health = 1500000000,
                    healthRegenPerYear = 250000000,
                    damage = 400000000,
                    speed = 375,
                    lifespan = 600000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 20,
                    intelligence = 100,
                    critPercent = 0.15f,
                    damagePercent = 0.15f,
                    healthPercent = 0.02f,
                    accuracy = 250,
                    range = 0,
                    knockback = 20,
                    knockbackResist = 20,
                    dodge = 100,
                    hit = 550,
                    weight = 500,
                    armorPercent = 556f,
                    scale = 0.35f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 900000000,
                    lingliRegenPerYear = 1000000,
                    yuanliMax = 100000000,
                    yuanliRegenPerYear = 50000,
                    nieliMax = 100000000,
                    nieliRegenPerYear = 5000
                },
                ["beast_01_stage"] = new CultivationStatsConfig
                {
                    stamina = 170,
                    health = 8500,
                    healthRegenPerYear = 85,
                    damage = 43,
                    speed = 13,
                    lifespan = 136,
                    command = 0,
                    organization = 0,
                    attackSpeed = 3,
                    intelligence = 9,
                    critPercent = 0.0085f,
                    damagePercent = 0.0085f,
                    healthPercent = 0.068f,
                    accuracy = 40,
                    range = 0,
                    knockback = 3,
                    knockbackResist = 3,
                    dodge = 40,
                    hit = 40,
                    weight = 43,
                    armorPercent = 19f,
                    scale = 0.03f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 500,
                    lingliRegenPerYear = 35,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["beast_02_stage"] = new CultivationStatsConfig
                {
                    stamina = 850,
                    health = 42500,
                    healthRegenPerYear = 850,
                    damage = 306,
                    speed = 25,
                    lifespan = 850,
                    command = 0,
                    organization = 0,
                    attackSpeed = 4,
                    intelligence = 17,
                    critPercent = 0.017f,
                    damagePercent = 0.017f,
                    healthPercent = 0.102f,
                    accuracy = 100,
                    range = 0,
                    knockback = 4,
                    knockbackResist = 4,
                    dodge = 100,
                    hit = 100,
                    weight = 68,
                    armorPercent = 33f,
                    scale = 0.05f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 1500,
                    lingliRegenPerYear = 80,
                    yuanliMax = 0,
                    yuanliRegenPerYear = 0,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["beast_03_stage"] = new CultivationStatsConfig
                {
                    stamina = 2125,
                    health = 85000,
                    healthRegenPerYear = 5100,
                    damage = 1870,
                    speed = 51,
                    lifespan = 5100,
                    command = 0,
                    organization = 0,
                    attackSpeed = 6,
                    intelligence = 26,
                    critPercent = 0.0255f,
                    damagePercent = 0.0255f,
                    healthPercent = 0.1275f,
                    accuracy = 140,
                    range = 0,
                    knockback = 6,
                    knockbackResist = 6,
                    dodge = 140,
                    hit = 140,
                    weight = 102,
                    armorPercent = 56f,
                    scale = 0.07f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 5000,
                    lingliRegenPerYear = 180,
                    yuanliMax = 50,
                    yuanliRegenPerYear = 1,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["beast_04_stage"] = new CultivationStatsConfig
                {
                    stamina = 4250,
                    health = 425000,
                    healthRegenPerYear = 85000,
                    damage = 23800,
                    speed = 85,
                    lifespan = 85000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 8,
                    intelligence = 34,
                    critPercent = 0.034f,
                    damagePercent = 0.034f,
                    healthPercent = 0.17f,
                    accuracy = 180,
                    range = 0,
                    knockback = 8,
                    knockbackResist = 8,
                    dodge = 180,
                    hit = 180,
                    weight = 128,
                    armorPercent = 75f,
                    scale = 0.10f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000,
                    lingliRegenPerYear = 300,
                    yuanliMax = 100,
                    yuanliRegenPerYear = 10,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["beast_05_stage"] = new CultivationStatsConfig
                {
                    stamina = 5100,
                    health = 1275000,
                    healthRegenPerYear = 255000,
                    damage = 68000,
                    speed = 102,
                    lifespan = 255000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 9,
                    intelligence = 43,
                    critPercent = 0.0425f,
                    damagePercent = 0.0425f,
                    healthPercent = 0.187f,
                    accuracy = 200,
                    range = 0,
                    knockback = 9,
                    knockbackResist = 9,
                    dodge = 200,
                    hit = 200,
                    weight = 153,
                    armorPercent = 96f,
                    scale = 0.14f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 20000,
                    lingliRegenPerYear = 500,
                    yuanliMax = 300,
                    yuanliRegenPerYear = 20,
                    nieliMax = 0,
                    nieliRegenPerYear = 0
                },
                ["beast_06_stage"] = new CultivationStatsConfig
                {
                    stamina = 5950,
                    health = 3825000,
                    healthRegenPerYear = 765000,
                    damage = 221000,
                    speed = 119,
                    lifespan = 1360000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 10,
                    intelligence = 51,
                    critPercent = 0.051f,
                    damagePercent = 0.051f,
                    healthPercent = 0.204f,
                    accuracy = 220,
                    range = 0,
                    knockback = 10,
                    knockbackResist = 10,
                    dodge = 240,
                    hit = 240,
                    weight = 187,
                    armorPercent = 122f,
                    scale = 0.18f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 50000,
                    lingliRegenPerYear = 1000,
                    yuanliMax = 500,
                    yuanliRegenPerYear = 30,
                    nieliMax = 20,
                    nieliRegenPerYear = 1
                },
                ["beast_07_stage"] = new CultivationStatsConfig
                {
                    stamina = 6800,
                    health = 12750000,
                    healthRegenPerYear = 2550000,
                    damage = 1105000,
                    speed = 140,
                    lifespan = 5100000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 11,
                    intelligence = 60,
                    critPercent = 0.0595f,
                    damagePercent = 0.0595f,
                    healthPercent = 0.221f,
                    accuracy = 240,
                    range = 0,
                    knockback = 11,
                    knockbackResist = 11,
                    dodge = 290,
                    hit = 290,
                    weight = 213,
                    armorPercent = 150f,
                    scale = 0.22f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 100000,
                    lingliRegenPerYear = 3000,
                    yuanliMax = 1000,
                    yuanliRegenPerYear = 50,
                    nieliMax = 100,
                    nieliRegenPerYear = 5
                },
                ["beast_08_stage"] = new CultivationStatsConfig
                {
                    stamina = 8330,
                    health = 119000000,
                    healthRegenPerYear = 25500000,
                    damage = 25500000,
                    speed = 204,
                    lifespan = 85000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 13,
                    intelligence = 68,
                    critPercent = 0.068f,
                    damagePercent = 0.068f,
                    healthPercent = 0.2465f,
                    accuracy = 280,
                    range = 0,
                    knockback = 13,
                    knockbackResist = 13,
                    dodge = 410,
                    hit = 410,
                    weight = 247,
                    armorPercent = 180f,
                    scale = 0.26f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 2000000,
                    lingliRegenPerYear = 20000,
                    yuanliMax = 20000,
                    yuanliRegenPerYear = 500,
                    nieliMax = 2500,
                    nieliRegenPerYear = 50
                },
                ["beast_09_stage"] = new CultivationStatsConfig
                {
                    stamina = 9350,
                    health = 170000000,
                    healthRegenPerYear = 38250000,
                    damage = 47600000,
                    speed = 234,
                    lifespan = 136000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 14,
                    intelligence = 77,
                    critPercent = 0.085f,
                    damagePercent = 0.085f,
                    healthPercent = 0.272f,
                    accuracy = 380,
                    range = 0,
                    knockback = 14,
                    knockbackResist = 14,
                    dodge = 650,
                    hit = 600,
                    weight = 281,
                    armorPercent = 260f,
                    scale = 0.30f,
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 10000000,
                    lingliRegenPerYear = 50000,
                    yuanliMax = 100000,
                    yuanliRegenPerYear = 2000,
                    nieliMax = 8000,
                    nieliRegenPerYear = 200
                },
                ["beast_10_stage"] = new CultivationStatsConfig
                {
                    stamina = 15300,
                    health = 1200000000,
                    healthRegenPerYear = 212500000,
                    damage = 340000000,
                    speed = 319,
                    lifespan = 510000000,
                    command = 0,
                    organization = 0,
                    attackSpeed = 17,
                    intelligence = 85,
                    critPercent = 0.1275f,
                    damagePercent = 0.1275f,
                    healthPercent = 0.02f,
                    accuracy = 235,
                    range = 0,
                    knockback = 17,
                    knockbackResist = 17,
                    dodge = 85,
                    hit = 490,
                    weight = 425,
                    armorPercent = 400f,
                    scale = 0.35f,              
                    speedMultiplier = 0f,
                    areaOfEffect = 0,
                    targets = 0,
                    lingliMax = 900000000,
                    lingliRegenPerYear = 1000000,
                    yuanliMax = 100000000,
                    yuanliRegenPerYear = 50000,
                    nieliMax = 100000000,
                    nieliRegenPerYear = 5000
                },
                ["path_01_demonic"] = new CultivationStatsConfig
                {
                    critPercent = 0.05f
                },
                ["path_02_immortal"] = new CultivationStatsConfig
                {
                },
                ["path_03_beast"] = new CultivationStatsConfig
                {
                    damagePercent = 0.05f
                },
                ["path_04_ancient"] = new CultivationStatsConfig
                {
                    armorPercent = 60f
                }
            };
        public static bool TryGetRealmConfig(string traitId, out CultivationStatsConfig config)
            => _realmConfigs.TryGetValue(traitId, out config);
        public static void ApplyRealmBaseStats(ActorTrait trait)
        {
            if (trait == null || string.IsNullOrEmpty(trait.id)) return;
            var bs = trait.base_stats;
            if (bs == null) { bs = new BaseStats(); trait.base_stats = bs; }
            if (!TryGetRealmConfig(trait.id, out var cfg)) return;
            SafeAdd(bs, strings.S.health, cfg.health);
            SafeAdd(bs, strings.S.damage, cfg.damage);
            if (cfg.armorPercent != 0f) SafeAdd(bs, strings.S.armor, cfg.armorPercent);
            SafeAdd(bs, strings.S.speed, cfg.speed);
            SafeAdd(bs, strings.S.lifespan, cfg.lifespan);
            SafeAdd(bs, strings.S.stamina, cfg.stamina);
            SafeAdd(bs, strings.S.intelligence, cfg.intelligence);
            SafeAdd(bs, strings.S.attack_speed, cfg.attackSpeed);
            SafeAdd(bs, strings.S.warfare, cfg.command);
            SafeAdd(bs, strings.S.stewardship, cfg.organization);
            if (cfg.critPercent != 0f) SafeAdd(bs, strings.S.critical_chance, cfg.critPercent);
            if (cfg.damagePercent != 0f) SafeAdd(bs, strings.S.multiplier_damage, cfg.damagePercent);
            if (cfg.healthPercent != 0f) SafeAdd(bs, strings.S.multiplier_health, cfg.healthPercent);
            if (cfg.scale != 0f) SafeAdd(bs, strings.S.scale, cfg.scale);
            if (cfg.speedMultiplier != 0f) SafeAdd(bs, strings.S.multiplier_speed, cfg.speedMultiplier);
            SafeAdd(bs, strings.S.mass_2, cfg.weight);
            SafeAdd(bs, strings.S.range, cfg.range);
            SafeAdd(bs, strings.S.area_of_effect, cfg.areaOfEffect);
            SafeAdd(bs, strings.S.targets, cfg.targets);
            SafeAdd(bs, strings.S.knockback, cfg.knockback);
            if (cfg.dodge != 0) SafeAdd(bs, "Dodge", cfg.dodge);
            int acc = (cfg.hit != 0 ? cfg.hit : cfg.accuracy);
            if (acc != 0) SafeAdd(bs, "Accuracy", acc);
            if (cfg.knockbackResist != 0) SafeAdd(bs, "Resist", cfg.knockbackResist);
            if (cfg.healthRegenPerYear != 0) SafeAdd(bs, "Healback", cfg.healthRegenPerYear);
            SafeAdd(bs, "LingliMax", cfg.lingliMax);
            SafeAdd(bs, "LingliRegenPerYear", cfg.lingliRegenPerYear);
            SafeAdd(bs, "YuanliMax", cfg.yuanliMax);
            SafeAdd(bs, "YuanliRegenPerYear", cfg.yuanliRegenPerYear);
            SafeAdd(bs, "NieliMax", cfg.nieliMax);
            SafeAdd(bs, "NieliRegenPerYear", cfg.nieliRegenPerYear);
        }
        private static void SafeAdd(BaseStats bs, string key, float val)
        {
            if (bs == null || string.IsNullOrEmpty(key) || val == 0f) return;
            var lib = AssetManager.base_stats_library;
            if (lib == null || lib.get(key) == null)
            {
                UnityEngine.Debug.Log($"[XN] Skip unknown base stat key: {key}");
                return;
            }
            try
            {
                bs[key] = bs[key] + val;
            }
            catch
            {
            }
        }
    }
}